
#include "RenderTypes.h"

extern ContextBaseId camera_context_base_id;

extern ContextBaseId lightvector_base_id;
extern ContextBaseId tex_simplemodel_context_base_id;
extern ContextBaseId flat_simplemodel_context_base_id;
extern ContextBaseId skybox_context_base_id;
extern ContextBaseId explosion_context_base_id;

extern ContextBaseId postproc_context_base_id;

extern ModelBaseId simple_modelbase_id;
extern ModelBaseId dot_modelbase_id;

extern ModelBaseId fullscreen_modelbase_id;

extern InstanceBaseId textured_instance_base_id;
extern InstanceBaseId flat_instance_base_id;
extern InstanceBaseId skybox_instance_base_id;
extern InstanceBaseId shot_instance_base_id;
extern InstanceBaseId billboard_instance_base_id;

extern InstanceBaseId dirlight_instance_base_id;
extern InstanceBaseId single_instance_base_id;
extern InstanceBaseId bloom_instance_base_id;

extern ModelBaseId simplequad_base_id;
extern InstanceBaseId simplequad_instance_base_id;
